[build.environment]
	NODE_VERSION = "22"

[build]
	publish = ".vitepress/dist"
	command = "pnpm run build"

[dev]
	command = "pnpm run dev"
	targetPort = 5173
	autoLaunch = false
	framework = "#custom"

